### ISSUE TITLE
Source Clean Up

### ISSUE THREAD

**Issue by ncurran02** [SuperSteelYT/Emotes#2]
If you explore through the trees, it is messy, things are not suppose to be there.
https://github.com/SuperSteelYT/Emotes/tree/devel/src (Keep main folder)
https://github.com/SuperSteelYT/Emotes/tree/devel/src/main/java (`.yml` files can be deleted in this path)

When you are at it, do some formatting (If you're using NetBeans [Please use IntelliJ >.>], do `Alt` + `Shift` + `F` to [auto-format](https://netbeans.org/project_downloads/usersguide/shortcuts-80.pdf) the file you are in, or click the project folder in NetBeans and use the same shortcut to format the whole project) as well as some clean up.

Have fun.

**Comment by ajaxvp** [comment]
Cleaned up and ready to push
